# Generated by Django 5.2.5 on 2025-08-27 19:29

from django.db import migrations


def create_initial_todos(apps, schema_editor):
    Todo = apps.get_model("todo", "Todo")
    Todo.objects.create(title="Sleep", completed=False)
    Todo.objects.create(title="Eat", completed=True)
    Todo.objects.create(title="Code", completed=False)


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_todos),
    ]
